'use strict';

exports.__esModule = true;
var DELETE_VALUE = exports.DELETE_VALUE = 'DELETE_VALUE';
var INITIALIZE_GROUP = exports.INITIALIZE_GROUP = 'INITIALIZE_GROUP';
var INITIALIZE_STATE = exports.INITIALIZE_STATE = 'INITIALIZE_STATE';
var MARK_VALIDATED = exports.MARK_VALIDATED = 'MARK_VALIDATED';
var RESET_SUBMIT = exports.RESET_SUBMIT = 'RESET_SUBMIT';
var RESET_VALUES = exports.RESET_VALUES = 'RESET_VALUES';
var SET_ERRORS = exports.SET_ERRORS = 'SET_ERRORS';
var SET_GROUP = exports.SET_GROUP = 'SET_GROUP';
var SET_SUBMITTING = exports.SET_SUBMITTING = 'SET_SUBMITTING';
var SET_SUBMIT_FAILED = exports.SET_SUBMIT_FAILED = 'SET_SUBMIT_FAILED';
var SET_VALUE = exports.SET_VALUE = 'SET_VALUE';
var SHOW_ERRORS = exports.SHOW_ERRORS = 'SHOW_ERRORS';
var UPDATE_VALUE = exports.UPDATE_VALUE = 'UPDATE_VALUE';